import "./../sass/pages/projects.scss";
import { SiTailwindcss, SiExpress, SiMongodb } from "react-icons/si";
import TechImg from "./layouts/TechImg";

const Projects = () => {
  const html = <i className="fa-brands fa-html5"></i>;
  const css = <i className="fa-brands fa-css3-alt"></i>;
  const js = <i className="fa-brands fa-js"></i>;
  const react = <i className="fa-brands fa-react"></i>;
  const sass = <i className="fa-brands fa-sass"></i>;
  const node = <i className="fa-brands fa-node"></i>;
  const btsrp = <i className="fa-brands fa-bootstrap"></i>;
  const tlwnd = <SiTailwindcss />;
  const express = <SiExpress />;
  const mongoDb = <SiMongodb />;
  const store = [
    {
      id: 5,
      name: "Pedromedia",
      image: require("./../images/pedromedia.png"),
      stack: [html, css, sass, btsrp, js],
      reveal: "",
      link: "https://pedromedia.netlify.app",
      github_url: "https://github.com/F-Hamid/Pedromedia",
      description:
        "A styled and responsive website with services and contact information for a professional photographer.",
    },
    {
      id: 1,
      name: "Tattoo Artist",
      image: require("./../images/mexihenna.png"),
      stack: [html, js, tlwnd, react],
      reveal: "",
      link: "https://mexihenna.netlify.app/",
      github_url: "https://github.com/F-Hamid/",
      description:
        "Modern and styled website for the best Tattoo Artist in Denver Co.",
    },

    {
      id: 0,
      name: "Skill Up",
      image: require("./../images/skillup-chart.png"),
      stack: [sass, js, react, node, express, mongoDb],
      reveal: "reveal",
      link: "https://skill-up-webapp.herokuapp.com/",
      github_url: "https://github.com/F-Hamid/SKILLUP",
      description:
        "A big scale project that manage and track the learning path and skills added by the user and store the data of each skill.",
    },

    {
      id: 2,
      name: "Architecture and interior design ",
      image: require("./../images/architecht.png"),
      stack: [html, css, sass, btsrp, js],
      reveal: "reveal",
      link: "https://architect-interior-design.netlify.app/",
      github_url: "https://github.com/F-Hamid/Architecture-Interior-Website",
      description:
        "A styled and responsive web SPA for a Architecture and interior design agency.",
    },
    {
      id: 13,
      name: "Scientist Portfolio",
      image: require("./../images/heroSection.png"),
      stack: [html, css, js, tlwnd, react],
      reveal: "",
      link: "https://tallouanas.netlify.app/",
      github_url: "",
      description:
        "I provided my client with this pixel perfect website that gathers all his information, work, and professional skills. ",
    },

    {
      id: 3,
      name: "Budget App ",
      image: require("./../images/budgetapp.png"),
      stack: [html, css, sass, btsrp, js, react],
      reveal: "reveal",
      link: "https://budgetspa.netlify.app",
      github_url: "https://github.com/F-Hamid/Budget-App",
      description:
        "Single web page application for managing and keeping track of your budget.",
    },

    {
      id: 4,
      name: "Quote or joke",
      image: require("./../images/quoteorjoke.png"),
      stack: [html, css, js],
      reveal: "reveal",
      link: "https://quote-jocke.netlify.app/",
      github_url: "https://github.com/F-Hamid/Quote-or-Joke",
      description:
        "Single page application for some  wisdom quotes and funny jokes generated by two separate online APIs on one click.",
    },
  ];

  return (
    <>
      <section className="projects" id="projects">
        <div className="window-container container-1">
          <div className="window-blur"></div>
          <div className="window-1 window"></div>
        </div>
        <div className="window-container container-2">
          <div className="window-blur"></div>
          <div className="window-2 window"></div>
        </div>
        <div className="window-container container-3">
          <div className="window-blur"></div>
          <div className="window-3 window"></div>
        </div>

        <p className="presentation ">
          As a full-stack web developer, I bring a unique combination of
          technical expertise and creativity to every project I work on. I have
          a strong foundation in both front-end and back-end development, and
          have worked with various programming languages, frameworks, and
          libraries such as HTML, CSS, JavaScript, React, Node.js, Express, and
          MongoDB... . <br />I am dedicated to creating user-friendly and
          responsive web applications that deliver a seamless user experience. I
          thrive on challenges and am always looking for opportunities to learn
          new technologies and skills to improve my craft. My attention to
          detail, strong work ethic, and ability to work well within a team make
          me a valuable addition to any project. If you're looking for a skilled
          and motivated full-stack web developer to help bring your project to
          life, I am confident that my expertise and enthusiasm will make me the
          ideal candidate for the job.
        </p>
        <div className="header ">
          <h2 className="header-heading shine-text">Projects</h2>
          <hr className="header-bar" />
          <p className="header-text">
            My work reflects real life web applications, various skills and
            problem solving. To explore even more, check out the links below.
          </p>
        </div>
        <main className="projects-main">
          {store.map(
            ({
              description,
              id,
              github_url,
              name,
              link,
              image,
              reveal,
              stack,
            }) => {
              return (
                <div
                  key={id}
                  className={`projects-box projects-box_${id} 
                  ${reveal}`}
                >
                  <div className="card-text">
                    <h1 className="card-text_heading">{name} </h1>
                    <p className="card-text_p">{description}</p>
                  </div>
                  <img className="projects-box-img" src={image} alt="Github" />

                  <div className="projects-box_after">
                    <a href={link} target="_blank" rel="noreferrer">
                      <i className="fa-brands fa-chrome"></i>
                    </a>
                    <a href={github_url} target="_blank" rel="noreferrer">
                      <i className="fa-brands fa-github "></i>
                    </a>
                  </div>
                  <div className="projects-box_before">
                    <div className="stack-projects">{stack}</div>
                  </div>
                </div>
              );
            }
          )}
          <div className="tech-container">
            <TechImg />
          </div>
          <a className=" reveal more" href="/projects">
            <img
              className="more-img"
              src={require("./../images/cube1.png")}
              alt="cube2"
            />
            <h1 className="more-text">Explore More...</h1>
          </a>
        </main>
      </section>
    </>
  );
};

export default Projects;
